2021/11/03 16:36:12 | python_logging.py(83 行) | INFO| 开始记录执行开始时间-------
2021/11/03 16:36:13 | python_logging.py(83 行) | INFO| fun1执行一共花费0.007681369781494141秒-------
2021/11/03 16:36:13 | python_logging.py(83 行) | INFO| 开始记录执行开始时间-------
2021/11/03 16:36:14 | python_logging.py(83 行) | INFO| fun2执行一共花费0.004189729690551758秒-------
2021/11/03 16:36:14 | python_logging.py(83 行) | INFO| 开始记录执行开始时间-------
2021/11/03 16:36:15 | python_logging.py(87 行) | ERROR| 执行fun3函数过程中出错，错误原因为can't multiply sequence by non-int of type 'str'
